steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/composer'
    args: ['install', '--ignore-platform-reqs']
    
  # Run database migrations
  - name: 'gcr.io/$PROJECT_ID/IMAGE_NAME:$SHORT_SHA'
    entrypoint: 'php'
    args:
      - 'artisan'
      - 'migrate'
      - '--force'
      - '--no-interaction'


  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/IMAGE_NAME:$SHORT_SHA', '.']
